### PR TITLE
handle array of promises

### PR DESCRIPTION
**Pull request by pluederitz**
Problem:
Using border commands requires writing generator functions.
If multiple command based operations have to be executed,
they have to be evaluated sequentially,
because `Promise.all` is not working in this setup.

Solution:
Extend context executor to handle also array of promises.
(which uses `Promise.all` internally to evaluate them simulaneously)

### CODE REVIEW

**Comment by marcmenn** [comment]
How about making borders work with async-generators? This way promises could be handled in the generator the usual way. Then, we still need a way to run multiple border-commands (in maybe parallel). For that I kinda started an API in https://github.com/actano/rplan/blob/master/lib/data-access-server/multi.js

**Comment by pluederitz** [comment]
But this solution executes all operations sequentially (evaluate one promise after the next one)?
This seems not be effectivly if some operations need more time but would by handled in parallel by backend.

**Comment by marcmenn** [comment]
That's two different things: 
a) Promises in parallel: use async-generators and keep the whole yielding of promises out of borders
b) Commands in parallel (which might internally use promises): this must be handled by borders. The proposed function does this now only sequential and could be improved. But might be a generic API for that.

**Comment by andirotter** [comment]
what about Bluebird.mapSeries for sequentially executing generators? 
http://bluebirdjs.com/docs/api/promise.mapseries.html

**Comment by thrucker** [comment]
I don't see the necessity for the proposed solution. The problem could be solved easily by using `Promise.all` inside the generator which is executed:
```javascript
const ctx = new Context()
ctx.execute(function* () {
  const results = yield Promise.all([
    Promise.resolve(1),
    Promise.resolve(2),
    Promise.resolve(3),
  ])
  expect(results).to.deep.equal([1, 2, 3])
}())
```

As @marcmenn points out, there's a difference between running promises or commands in parallel. Due to the nature of generators and iterators, parallel command execution would need special support in `Context.execute`. I'll propose a solution for that problem in a new PR.

**Comment by pluederitz** [comment]
Due to the fact this solution doesn't solve the real problem (executing multiple generator functions/commands by `borders` backend in parallel) I close this PR.

**Pull request closed without merging**
